/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'deigote' at '7/2/14 8:18 PM' with Gradle 1.9
 *
 * @author deigote, @date 7/2/14 8:18 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
