/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'deigote' at '7/2/14 8:18 PM' with Gradle 1.9
 *
 * @author deigote, @date 7/2/14 8:18 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
